# joint_limits.yaml

# Set scaling factors to 1.0 for maximum velocity and acceleration
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  base_to_link1:
    has_velocity_limits: true
    max_velocity: 3.14        # ~180 deg/sec
    has_acceleration_limits: true
    max_acceleration: 5.0
  link1_to_link2:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
  link2_to_link3:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
  link3_to_link4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
  link4_to_link5:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0
  link5_to_gripper:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 5.0